Feat/35 content&round
b1-sycls/sycls pull request #77
Opened 2024-07-25 15:56 UTC by CKM123423

## 📌 연관된 이슈

> Main Issue Number : #35 
> Sub Issue Number : #36 #48 #50 #51 #52 #53 #59 #61 #62 #65 #66 #69 #70 #76 
> <br>
> resolved : #36 #48 #50 #51 #52 #53 #59 #61 #62 #65 #66 #69 #70 #76 

## PR 종류
해당 PR은 어떤 부분에 대한 변화인가요?

- [x] 버그 수정 `FIX`(Hotfix)
- [x] 코드 수정 `MODIFY`
- [x] 기능 추가 `FEAT`
- [ ] 파일 이름 변경 `RENAME`
- [ ] 테스트 코드 추가 `TEST`
- [ ] 코드 스타일 변화 (formatting, local variables) `STYLE`
- [x] 리팩토링 (no functional changes, no api changes) `REFACTOR`
- [x] 빌드 관련 내용 추가 및 변화 `BUILD`
- [ ] 문서 내용 추가 및 변화`DOCS`
- [ ] 기타 변경 사항 추 `CHORE`
- [ ] Other... (적어주세요 : )

## 💻 작업 내용
> 공연등록, 공연 수정, 공연 상태수정, 공연 조회기능
회차등록, 회차 수정, 회차 상태수정, 회차 조회기능

## 해당 PR이 다른 영역에 영향을 미치나요?
- [x] Yes
- [ ] No

### "Yes"를 선택한 경우, 어디에 영향을 끼치는지 적어주세요
> GlobalExceptionHandler 
Round Entity 컬럼
Status 코드
패키지 구조변경
Content Entity 변경
Round Entity 변경
data.sql변경
의존성 추가

2024-07-25 17:12 UTC, Chanwon-Seo commented on sycls-admin-api/src/main/java/com/b1/content/ContentService.java
> +        }
ContentStatus에서 해당 상태에 대해서 별도 메서드로 관리할 수 있을 것 같습니다.

2024-07-26 00:41 UTC, Chanwon-Seo approved these changes

2024-07-26 00:41 UTC, Chanwon-Seo commented on sycls-admin-api/src/main/java/com/b1/content/ContentService.java
> +        final List<ContentDetailImage> contentDetailImageList = getAndCreateContentDetailImages(
final을 제거 해주세요

2024-07-26 00:41 UTC, Chanwon-Seo commented on sycls-admin-api/src/main/java/com/b1/content/ContentService.java
> +        final List<ContentDetailImage> contentDetailImageList = getAndCreateContentDetailImages(
final을 제거 해주세요

2024-07-26 00:46 UTC, Chanwon-Seo requested changes
재검토 중입니다.

2024-07-26 01:17 UTC, Leejinuk123 approved these changes
코멘트에 언급한 부분들은 크리티컬한 이슈는 아니어서 Approve 올리겠습니다! 수정하시고 merge하시면 될 것 같네요.

2024-07-26 01:17 UTC, Leejinuk123 commented on sycls-common/src/main/java/com/b1/exception/errorcode/CategoryErrorCode.java
>      CATEGORY_NAME_DUPLICATED(HttpStatus.BAD_REQUEST.value(), "중복된 카테고리 이름 입니다. "),
중복된 값을 저장하려고 할 때 HttpStatus.CONFLICT 로 응답코드를 작성하는 방식도 좋아보입니다.
reference : https://geumba.tistory.com/78

2024-07-26 01:17 UTC, Leejinuk123 commented on sycls-common/src/main/java/com/b1/s3/S3Uploader.java
> +public class S3Uploader {
로깅 토픽이 클래스 네임과 일치하지 않은데.. 의도하신건가요?

2024-07-26 01:17 UTC, Leejinuk123 commented on sycls-core/src/main/java/com/b1/content/entity/ContentStatus.java
> +public enum ContentStatus {
해당 부분도 로깅 토픽이 클래스 명이랑 불일치합니다.

2024-07-26 01:20 UTC, CKM123423 commented on sycls-common/src/main/java/com/b1/s3/S3Uploader.java
> +public class S3Uploader {
아닙니다! 서비스였다가 이름변경한후 토픽을안바꿧네요 수정했습니다

2024-07-26 01:55 UTC, Chanwon-Seo approved these changes
확인했습니다.

2024-07-26 02:05 UTC, merged